version: '3.8'

services:
  # SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LogStream123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - logstream-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - logstream-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - logstream-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - logstream-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=logstream
      - RABBITMQ_DEFAULT_PASS=LogStream123!
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - logstream-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - logstream-network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=LogStream123!
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - logstream-network

  # LogStream API
  logstream-api:
    build:
      context: .
      dockerfile: src/LogStream.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=LogStreamDb;User Id=sa;Password=LogStream123!;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
    ports:
      - "7001:80"
    depends_on:
      - sql-server
      - redis
      - elasticsearch
    networks:
      - logstream-network

  # LogStream gRPC
  logstream-grpc:
    build:
      context: .
      dockerfile: src/LogStream.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=LogStreamDb;User Id=sa;Password=LogStream123!;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
    ports:
      - "7002:80"
    depends_on:
      - sql-server
      - redis
      - elasticsearch
    networks:
      - logstream-network

  # LogStream Web
  logstream-web:
    build:
      context: .
      dockerfile: src/LogStream.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=LogStreamDb;User Id=sa;Password=LogStream123!;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
      - ApiSettings__BaseUrl=http://logstream-api:80
    ports:
      - "7000:80"
    depends_on:
      - sql-server
      - redis
      - elasticsearch
      - logstream-api
    networks:
      - logstream-network

volumes:
  sqlserver-data:
  redis-data:
  elasticsearch-data:
  rabbitmq-data:
  prometheus-data:
  grafana-data:

networks:
  logstream-network:
    driver: bridge